project:
  type: book

book:
  title: "Oregon Extended Assessment Technical Documentation"
  authors:
    - "Brock Rowley"
    - "Chris Loan"
    - "Gerald Tindal"
  cover-image: img/stateofOR.png
  repo-url: https://github.com/UO-BRT/orext-techreport-template
  downloads: [pdf]
  date: "3/31/2022"
  chapters:
    - index.qmd
    - ce1.qmd
    - ce2.qmd
    - ce3.qmd
    - ce4.qmd
    - ce5.qmd
    - ce6.qmd
    - references.qmd
  appendices:
      - app1.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    echo: false
  pdf:
    documentclass: scrreprt
    echo: false



